pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:romaswe/passwordgenerator.git
          - cd passwordgenerator.git
          - git push --mirror git@github.com:romaswe/Passwordgenerator.git